name: Verwijderen pullrequest repository
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: docs-hpc-pr${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        uses: octobay/delete-repository-action@v1
        with:
          name: octobay/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}