name: Verwijderen pullrequest repository
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: docs-hpc-pr${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      # old method
      #- name: Delete repository for temporary deployment
      #  uses: octobay/delete-repository-action@v1
      #  with:
      #    name: uashogeschoolutrecht/${{ env.PR_REPO_NAME }}
      #    access-token: ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}

      - name: Delete repository for temporary deployment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}
          script: |
            github.rest.repos.delete({
              owner: context.repo.owner,
              repo: ${{ env.PR_REPO_NAME }},
            });          