name: Aanmaken acceptatie omgeving voor Pullrequest

on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

env:
  PR_REPO_NAME: datascience-pr${{ github.event.pull_request.node_id }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create new repository for temporary deployment
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Creating GitHub Organization Repository
        uses: repo-ctrl/create-repo-action@main 
        id: create-repo
        with:
          repo-name: '${{ env.PR_REPO_NAME }}'
          org-admin-token: '${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}'
        # When the repo already exist this gives an error, but this can be skipped
        continue-on-error: true
      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"                  

  pr-build-deploy:
    needs: create-repository
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com    

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: 'pr-build'

      - name: Setup Ruby
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: |
          cd pr-build
          bundle install
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          cd ..
        env:
          JEKYLL_ENV: production

      - name: Checkout temporary deployment target repo
        uses: actions/checkout@v3
        with:
          repository: uashogeschoolutrecht/${{ env.PR_REPO_NAME }}
          path: 'pr-deploy'
          token: ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}
        # because there is no branch on the repo there will be an error, because actions/checkout always reforms a checkout on main.
        # Only the git clone of the repo is needed
        continue-on-error: true

      - name: Push files to target
        run: |
          cp -r pr-build/_site/* pr-deploy
          cd pr-deploy
          touch .nojekyll
          git add .
          git commit -m $GITHUB_SHA
          git branch -M gh-pages
          git push -u origin gh-pages

      # First sleep, because the pr repo has to build the pages before it can be made public
      - name: Make github page public
        run: |
          run: sleep 40s
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/uashogeschoolutrecht/${{ env.PR_REPO_NAME }}/pages \
            -d '{"public":true}'
          
      - name: Place comment in pull request with link to page
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'link to page: https://uashogeschoolutrecht.github.io/${{ env.PR_REPO_NAME }}/'
            })         
    
