name: REPO aanmaken testje

on:
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Testje om een nieuw repo aan te maken
      run: |
        touch README.md
        git add .
        git commit -m "first commit"
        git remote add origin git@github.com:uashogeschoolutrecht/docs-hpc-pr-001.git
        git push -u origin master
