name: REPO aanmaken testje

on:
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  


env:
  PR_REPO_NAME: docs-hpc-pr-${{ github.event.pull_request.node_id }}

jobs:
  create-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Create new repository for temporary deployment
        uses: octobay/create-repository-action@v1
        with:
          name: ${{ env.PR_REPO_NAME }}
          org: octobay
          access-token: ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}
