name: Testje om page public te maken

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

env:
  PR_REPO_NAME: docs-hpc-pr${{ github.event.pull_request.node_id }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  make-public:
    runs-on: ubuntu-latest
    name: maak publiek
    steps:
      - name: do it
        run: |
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/uashogeschoolutrecht/docs-hpc-prPR_kwDOEb1X_85HPc4Q/pages \
            -d '{"public":"true"}'  

    
