name: REPO aanmaken testje

on:
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  


env:
  PR_REPO_NAME: docs-hpc-pr-${{ github.event.pull_request.node_id }}

jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Creating Organization Repository
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Creating GitHub Organization Repository
        uses: repo-ctrl/create-repo-action@main 
        id: create-repo
        with:
          repo-name: '${{ env.PR_REPO_NAME }}'
          org-admin-token: '${{ secrets.PRIVE_ACCESS_TOKEN_FOR_PR_ACTION }}'
      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo.outputs.repo-url }}"          
